[tool.poetry]
name = "herokuapp"
version = "0.0.1"
description = ""
authors = ["Axel,Schouten"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
fastapi = "0.109.2"
gunicorn = "21.2.0"


[tool.poetry.group.dev.dependencies]
uvicorn = "0.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
