[tool.poetry]
name = "herokuapp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.7"
fastapi = "0.109.2"


[tool.poetry.group.dev.dependencies]
uvicorn = "0.27.1"
simple-salesforce = "1.12.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
